version: 0.1

phases:
  pre_build:
    commands:
      - echo Pull loadimpact/k6 image..
      - docker pull loadimpact/k6
  build:
    commands:
      - echo Run performance test
      - cat scripts/test.js | docker run -i loadimpact/k6 run -
  post_build:
    commands:
      - echo Performance test complete